### ISSUE TITLE
Third party libraries extensions

### ISSUE THREAD

**Issue by stanislavfeldman** [FutureKit/FutureKit#12]
I am using some third party libraries in my projects such as Parse and Net.
So I am going to write FutureKit extensions for them.
Should I put these extensions inside FutureKit in some folder or should I create a different repo for them?

**Comment by mishagray** [comment]
This is an excellent question!  

I've been trying to decide now to deal with this.   As I have an AlamoFire extension I want to release too. 

We need to make sure that people using Carthage and Cocoapods don't have too many unwanted 3rd party dependencies showing up int their projects.   But I'm also afraid of repo creep. 

I haven't tested Carthage as much as Cocoapods.   I know Cocoapods has some support for "optional" sub-pods.   But if people are moving more to Carthage than I guess we have to figure this out. 

If you want to put them inside a folder in the repo for now, that's ok.  But we may need to make sure they don't automatically get added by the pod spec file, before I can merge the stuff into the master. 

What I mean to do is to try both strategies (different repos vs subpods)  and figure out which looks easier to maintain and which is easier for people to drop into their projects.  

Are there any other projects that have done this right?

**Comment by stanislavfeldman** [comment]
I've partially integrated with MapKit and Net.
I created repo https://github.com/stanislavfeldman/FutureKit-Extensions and published these extensions.
Feel free to fork.
