### ISSUE TITLE
Never-ending process when building or archiving.

### ISSUE THREAD

**Issue by gundlev** [FutureKit/FutureKit#25]
Hi

I added FutureKit to my project manually and it works great when i build it and test, but whenever i try to archive and it gets to FutureKit iOS it spins up a swift process taking up 99% CPU and never gets further than in building than "Compiling Swift source files". I also tried just opening the project and running it in order to build the framework and just import that, but the same thing happens. The same thing also happens if i use carthage.

**Comment by mishagray** [comment]
Which version of Xcode are you using?

**Comment by gundlev** [comment]
Version 7.2 (7C68)

**Comment by mishagray** [comment]
Sigh.   Whole-Module-optimziation is hanging.  Or maybe it just wants like 15 mins to compiler or something evil.

If you change the Release settings in "Swift Compiler - Code Generation"
from "Fast, Whole Module Optimization" to "Fast" it fixes the problem.

That isn't a huge optimization, and apparently we aren't the only library I have seen have issues with it.

Putting out a patch to change the default settings for people.

**Comment by mishagray** [comment]
Fixed:
https://github.com/FutureKit/FutureKit/pull/26
