### ISSUE TITLE
Question: FutureKit 2.0 changes

### ISSUE THREAD

**Issue by o15a3d4l11s2** [FutureKit/FutureKit#48]
Is there a changelog or any description of the changes made in FutureKit 2.0?

**Comment by mishagray** [comment]
1) So The biggest change is that most of the onSuccess/onFail etc are now defined inside of a protocol extension NOT a method on Future.

There are is also now a 'CompletionType' protocol.   Which is basically 'any object that can be resolved to a completion value'.    So now Completion<T>, FutureResult<T>, Future and Promise are all 'CompletionType's.    

And the onSuccess and onComplete allow you to return 'any' Completion type you want from a method.  (Future, Promise, Completion<T>, FutureResult<T>) as long as you are consistant with every return path always returning the same type (you can't return a Future in one sport and a Completion<T> in some other exit path).

It also means you could wrap Any 'future-like' object you want with the CompletionType protocol, and they will be treated like onCompletion handlers.
This seems to work much better with the Swift 2.0 type inference engine.

2) Error handling is better.  ALL of the blocks handlers now just let your 'try' or 'throw' anywhere.  Without needing to wrap the things in 'do'...'catch'.  Which can simplify error handling. 
You can also use a Protocol extension if you want to 'map' some of your Errors into cancellations. This is useful for wrapping other APIS that treat cancellation like an error.  
If you extend your errors using 'ErrorTypeMightBeCancellation' and define the method isCancellation, than those errors will automatically be 'converted' into Cancellations by FutureKit.  And your 'onFail' methods won't be called.  This is keeps 'onFail' handlers focused on errors, not cancellations (like it's designed to).


3) Cancelation works SLIGHTLY differently in the case where you have a 'tree' of dependent futures.  THis can happen if the same future has two independent dependent futures.  (As apposed to a more typical "chain" of futures where everything is cleanly dependent on a single future).    Now if anyone 'child' cancels, the entire 'tree' of futures is canceled.   Which seems to be less confusing.  The old behavior had the 'parent' ignore a cancellation request if he multiple 'children' and only one of them sent the cancel.  This behavior is still supported via an option, but that seems to lead to confusion for most people.

4) The 'type erased' FutureAny works different.  But it's still not as good as at could be, so I expect that FutureAny is going to get refactored a bit in the next release.   So you can define methods that return a Future, but don't need to define a specific type.  It's still awkward to case things from future to futureAny etc.   If you don't care about type erasure, it's not a big deal.

**Comment by o15a3d4l11s2** [comment]
Thanks a lot for the details.
