### ISSUE TITLE
Better description under title

### ISSUE THREAD

**Issue by lfarah** [FutureKit/FutureKit#50]
<img width="368" alt="screen shot 2016-08-03 at 4 08 06 pm" src="https://cloud.githubusercontent.com/assets/6511079/17378479/7cc26c4c-5994-11e6-8355-fe7efb92de8e.png">
Should be something like:
> A Swift based Future/Promises Library for IOS and OS X. http://futurekit.org

**Comment by tommybananas** [comment]
So just adding the link? The link is at the top in the project description.

**Comment by lfarah** [comment]
Noo, you should put a simple description, like:
> A Swift based Future/Promises Library for IOS and OS X.

**Comment by mishagray** [comment]
better?

**Comment by lfarah** [comment]
Perfect!
