### ISSUE TITLE
[question] flatmap for futures?

### ISSUE THREAD

**Issue by klundberg** [FutureKit/FutureKit#58]
I was playing around with futurekit last week and ran into a weird roadblock, in that I couldn't return a future in an onSuccess block and have that future be the one that is chained on moving forward, making it effectively a flatmap operation. Is this something that was tried and just didn't work, or is this a feature that can be made to work if someone puts the time in? I wouldn't be averse to trying it out if there's no technical or other reason not to.

Thanks!

**Comment by mishagray** [comment]
It should work fine. 

There are different versions of onSuccess and the compiler usually picks the right one.   It can often help to define the return types in your blocks.   

But it is looking either for a new value or a "CompletionType" which can be a Future or Completion enum.  

Do you have a snippet that fails?

**Comment by klundberg** [comment]
Hm, I tried creating a small snippet that fails but it worked as expected like you said. The code I was writing initially that hit this issue was throwaway prototype code that I worked on last week, so if I ever revisit it I'll try to reproduce the problem there, but I'll close this until then.
