### ISSUE TITLE
Allow futurekit to build via carthage with Xcode 9

### ISSUE THREAD

**Issue by klundberg** [FutureKit/FutureKit#66]
Currently when I try to build FutureKit 3.0.0 with carthage and Xcode 9, I get build errors (see [this gist](https://gist.github.com/klundberg/613a92494f32fe1041c196ac152ed483) for the build output). We want to experiment with xcode 9 but can't until this is resolved. Is this just a project settings tweak or is there something more fundamental that the Xcode 9 compiler in swift 3 mode expects that futurekit isn't doing?

**Comment by mishagray** [comment]
Gonna try and release a version an Swift 3.2/XCode 9 compatible release ASAP.   
You could also aim your Cathage file at @bestwnh's branch here:

https://github.com/FutureKit/FutureKit/pull/65
 (In Carthage I think you just change the line to ```github "bestwnh/FutureKit" ).


Will also follow-up with a Swift 4.0 version also.   

I expect to see FutureKit 3.2 and 4.0 branches showing up in the next few days. (for Swift 3.2 and Swift 4.0 respectively).   FutureKit 3.0 will stay as the 3.x/XCode 8 supported branch...

**Comment by klundberg** [comment]
@mishagray great, thank you so much!

**Comment by mishagray** [comment]
Some official branches:
https://github.com/FutureKit/FutureKit/tree/xcode9
https://github.com/FutureKit/FutureKit/tree/xcode9-swift4

The differences between 3.2 and 4.0 seem VERY small, but there look to be some very small 'breaking' fixes that 90% of users won't hit. (Unless you were using some of the low-level internal Executor wrapping methods etc). 
And it looks like the required 4.0 changes would also compile in Swift 3.2 without issues.   So considering just making the code Swift 4.0 based.  

If people want to test in their projects PLEASE do.  All I have done so far is run all the existing test cases.   

Still need to update the ReadME, Playgrounds and probably add a few test cases.  But the port looks pretty close to ready...

Carthage users can drop this in the Cartfile
``` github "FutureKit/FutureKit" "xcode9-swift4" ```

Cocoapods 
```   pod 'FutureKit', :git => 'https://github.com/FutureKit/FutureKit.git', :branch => 'xcode9-swift4' ```
