### ISSUE TITLE
mapAsOptional() has impossible function signature

### ISSUE THREAD

**Issue by slavapestov** [FutureKit/FutureKit#67]
In Xcode 9 beta 1, this function no longer compiles:

```
    public func mapAsOptional<O : OptionalProtocol>() -> Completion<O.Wrapped?> {

        return self.map { v -> O.Wrapped? in
            return v as? O.Wrapped
        }

    }
```

This is because when calling it there is no way to infer the generic parameter for 'O' (try it in 8.3 -- you can't actually call this function).

Previously we would allow such definitions that cannot be called, but now we reject them. I think you can just remove the function in question, or change it to the following:

```
    public func mapAsOptional<Wrapped>() -> Completion<Wrapped?> {
      ...
    }
```

**Comment by slavapestov** [comment]
Looks like this is already being worked on -- https://github.com/FutureKit/FutureKit/pull/65/files

**Comment by mishagray** [comment]
checkout Some official branches:
https://github.com/FutureKit/FutureKit/tree/xcode9
https://github.com/FutureKit/FutureKit/tree/xcode9-swift4

I kept the method... but know you have to pass the 'desired' type through.

ex:
```f. mapAsOptional(Integer.self)```
