### ISSUE TITLE
Combining multiple requests

### ISSUE THREAD

**Issue by jayesh15111988** [FutureKit/FutureKit#70]
I am looking for a way where FutureKit would allow combining multiple requests. For example, I have requests, request1 and request2. I want to fire them simultaneously and wait until both requests return the result. I also want to make sure results are returned in order.

If I fire request1 and request2 and they return data1 and data2 respectively, the API should return data1 and data2 serially in order. I was wondering if this is something possible with current FutureKit implementation.

To give more context this could be more like [combineLatest](http://reactivex.io/documentation/operators/combinelatest.html) signal from ReactiveCocoa.

**Comment by mishagray** [comment]
there is combineFuture already.. (which was very inspired by combineLatest).


``` combineFutures(asyncFuncA(), asyncFuncB()).onSuccess { (resultA, resultB) in  ... } ```

It does syntactic sugar around FutureBatch (which is better for an arbitrary list of futures).

ALSO cancellations works as you expect.  If you cancel the 'combined' future it should cancel each of the futures.

FutureBatch can also be used if you want to get a future that returns the individual 'result' of each subFuture.  And control if the failure one subfigure should 'auto-cancel' the others.

combineFutures() will always 'fail' if any of the sub-futures fail, with the result of the 'first' failure.
