### ISSUE TITLE
Build error on Xcode 9 Beta 3

### ISSUE THREAD

**Issue by jayesh15111988** [FutureKit/FutureKit#72]
I am using Carthage dependency to load `FutureKit` in our project. However, during build phase it is failing with following error on Xcode 9 Beta 3. (Screenshot attached).

Adding following line in the `Error extension` seems to be fixing the build error. 

```swift
var userInfo: [AnyHashable: Any] { return [:] }
```

Just want to confirm if this is a legit error and then we can put PR to fix it
<img width="821" alt="screen shot 2017-07-27 at 4 52 08 pm" src="https://user-images.githubusercontent.com/6687735/28691913-8704fcca-72ec-11e7-801f-a0c7ecdf5661.png">

**Comment by mishagray** [comment]
Does this happen if you change your Carthage file to:
``` github "FutureKit/FutureKit" "xcode9-swift4" ```

??

**Comment by jayesh15111988** [comment]
Yes, I tried both available branches. `xcode9-swift4` and `xcode9`. Both of them gave me the same error. We were wondering if it is fine to make pull request with our fix.

**Comment by mishagray** [comment]
yeah.. please do...

**Comment by jayesh15111988** [comment]
PR submitted here https://github.com/FutureKit/FutureKit/pull/73
